name: Scan Code

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:

  sonarqube:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.8.0

      - name: Build Docker image
        run: docker build -t android-sdk-image -f Dockerfile .

      - name: Run SonarQube scan
        run: |
          docker run \
            -v ${{ github.workspace }}:/app \
            -w /app \
            -e SONAR_TOKEN \
            -e SONAR_HOST_URL \
            android-sdk-image \
            ./gradlew sonarqube